services:
  - type: web
    name: eloy-back-timer
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false        # We'll paste this manually in Render dashboard
      - key: RAILS_ENV
        value: production

databases:
  - name: eloy-back-timer-db
    plan: free
    databaseName: eloy_back_timer_production