default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>

development:
  <<: *default
  database: eloy_back_timer_development

test:
  <<: *default
  database: eloy_back_timer_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: eloy_back_timer_production
  cache:
    <<: *primary_production
    database: eloy_back_timer_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: eloy_back_timer_production_queue
    migrations_paths: db/queue_migrate